org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
android.suppressUnsupportedCompileSdk=36

# R8 Full Mode & Resource Optimization for maximum performance & minimum memory footprint
android.enableR8.fullMode=true
android.enableResourceOptimizations=true
